// <auto-generated />
using System;
using EquipmentMonitor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentMonitor.Migrations
{
    [DbContext(typeof(EquipmentMonitorDbContext))]
    [Migration("20241020195307_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("EquipmentMonitor.Models.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdated = new DateTime(2024, 10, 20, 19, 53, 7, 696, DateTimeKind.Utc).AddTicks(5070),
                            Location = "Location1",
                            Name = "Equipment1",
                            State = 2
                        },
                        new
                        {
                            Id = 2,
                            LastUpdated = new DateTime(2024, 10, 20, 19, 53, 7, 696, DateTimeKind.Utc).AddTicks(5070),
                            Location = "Location2",
                            Name = "Equipment2",
                            State = 0
                        },
                        new
                        {
                            Id = 3,
                            LastUpdated = new DateTime(2024, 10, 20, 19, 53, 7, 696, DateTimeKind.Utc).AddTicks(5070),
                            Location = "Location1",
                            Name = "Equipment3",
                            State = 1
                        });
                });

            modelBuilder.Entity("EquipmentMonitor.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "No Description",
                            EquipmentId = 1,
                            ProductId = 1,
                            Quantity = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "No Description",
                            EquipmentId = 2,
                            ProductId = 2,
                            Quantity = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "No Description",
                            EquipmentId = 3,
                            ProductId = 1,
                            Quantity = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "No Description",
                            EquipmentId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "No Description",
                            EquipmentId = 2,
                            ProductId = 1,
                            Quantity = 4,
                            Status = 0
                        });
                });

            modelBuilder.Entity("EquipmentMonitor.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product2"
                        });
                });

            modelBuilder.Entity("EquipmentMonitor.Models.Entities.Order", b =>
                {
                    b.HasOne("EquipmentMonitor.Models.Entities.Equipment", "Equipment")
                        .WithMany("Orders")
                        .HasForeignKey("EquipmentId");

                    b.HasOne("EquipmentMonitor.Models.Entities.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EquipmentMonitor.Models.Entities.Equipment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EquipmentMonitor.Models.Entities.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
